name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Prepare for production
        run: |
          rm .gitignore
          mv .deploy.gitignore .gitignore
          rm -rf .github
          rm -rf .idea
          rm -rf .vscode
          rm -rf build
          rm -rf tests
          rm phpunit.xml.dist

      - name: Create a built branch
        run: |
          BRANCH_NAME=$(echo $GITHUB_REF | grep -oP '(?<=refs\/heads\/).*')
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action CI"
          git remote set-url origin https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git
          git checkout -b $BRANCH_NAME-built
          git add -A && git commit -m "built from $GITHUB_SHA"
          git push --force -u origin $BRANCH_NAME-built
